Update patch set 3
Patch Set 3: Code-Review+1

Assuming failed tests will be fixed in SIMP 6:

- spec tests: Nearly all fail
- acceptance tests fail:
 1) apache parameters default_confd_files => false doesnt do anything
     Failure/Error: apply_manifest(pp, :catch_failures => true)
     Beaker::Host::CommandFailure:
       Host 'centos-64-x64' exited with 1 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.lpsNn6
       Last 10 lines of output were:
       	Info: Loading facts
       	Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class apache at /tmp/apply_manifest.pp.lpsNn6:1 on node centos-64-x64.tasty.bacon
       	Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class apache at /tmp/apply_manifest.pp.lpsNn6:1 on node centos-64-x64.tasty.bacon

Patch-set: 3
Reviewer: lnemsick.simp@gmail.com <1008746@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=+1